
import { BibleBook } from './types.ts';

export const BIBLE_BOOKS: BibleBook[] = [
  // Old Testament (Sastro Gitcham)
  { id: 'gen', name: 'Gital Gachengani', englishName: 'Genesis', chapters: 50, testament: 'Old' },
  { id: 'exo', name: 'Ong·katangani', englishName: 'Exodus', chapters: 40, testament: 'Old' },
  { id: 'lev', name: 'Levitiko', englishName: 'Leviticus', chapters: 27, testament: 'Old' },
  { id: 'num', name: 'Chan·ani', englishName: 'Numbers', chapters: 36, testament: 'Old' },
  { id: 'deu', name: 'Duiteronomi', englishName: 'Deuteronomy', chapters: 34, testament: 'Old' },
  { id: 'jos', name: 'Joshua', englishName: 'Joshua', chapters: 24, testament: 'Old' },
  { id: 'jud', name: 'Bichal Ka·giparang', englishName: 'Judges', chapters: 21, testament: 'Old' },
  { id: 'rut', name: 'Ruth', englishName: 'Ruth', chapters: 4, testament: 'Old' },
  { id: '1sa', name: '1 Samuel', englishName: '1 Samuel', chapters: 31, testament: 'Old' },
  { id: '2sa', name: '2 Samuel', englishName: '2 Samuel', chapters: 24, testament: 'Old' },
  { id: '1ki', name: '1 Rajarang', englishName: '1 Kings', chapters: 22, testament: 'Old' },
  { id: '2ki', name: '2 Rajarang', englishName: '2 Kings', chapters: 25, testament: 'Old' },
  { id: '1ch', name: '1 Itihas', englishName: '1 Chronicles', chapters: 29, testament: 'Old' },
  { id: '2ch', name: '2 Itihas', englishName: '2 Chronicles', chapters: 36, testament: 'Old' },
  { id: 'ezr', name: 'Ezra', englishName: 'Ezra', chapters: 10, testament: 'Old' },
  { id: 'neh', name: 'Nehemiah', englishName: 'Nehemiah', chapters: 13, testament: 'Old' },
  { id: 'est', name: 'Esther', englishName: 'Esther', chapters: 10, testament: 'Old' },
  { id: 'job', name: 'Job', englishName: 'Job', chapters: 42, testament: 'Old' },
  { id: 'psa', name: 'Gitrang', englishName: 'Psalms', chapters: 150, testament: 'Old' },
  { id: 'pro', name: 'Toe Skianirang', englishName: 'Proverbs', chapters: 31, testament: 'Old' },
  { id: 'ecc', name: 'Skigipa', englishName: 'Ecclesiastes', chapters: 12, testament: 'Old' },
  { id: 'sng', name: 'Solomon-ni Git', englishName: 'Song of Solomon', chapters: 8, testament: 'Old' },
  { id: 'isa', name: 'Isaia', englishName: 'Isaiah', chapters: 66, testament: 'Old' },
  { id: 'jer', name: 'Jeremia', englishName: 'Jeremiah', chapters: 52, testament: 'Old' },
  { id: 'lam', name: 'Kal·imani', englishName: 'Lamentations', chapters: 5, testament: 'Old' },
  { id: 'eze', name: 'Ezekiel', englishName: 'Ezekiel', chapters: 48, testament: 'Old' },
  { id: 'dan', name: 'Daniel', englishName: 'Daniel', chapters: 12, testament: 'Old' },
  { id: 'hos', name: 'Hosea', englishName: 'Hosea', chapters: 14, testament: 'Old' },
  { id: 'joe', name: 'Joel', englishName: 'Joel', chapters: 3, testament: 'Old' },
  { id: 'amo', name: 'Amos', englishName: 'Amos', chapters: 9, testament: 'Old' },
  { id: 'oba', name: 'Obadia', englishName: 'Obadiah', chapters: 1, testament: 'Old' },
  { id: 'jon', name: 'Jona', englishName: 'Jonah', chapters: 4, testament: 'Old' },
  { id: 'mic', name: 'Mika', englishName: 'Micah', chapters: 7, testament: 'Old' },
  { id: 'nah', name: 'Nahum', englishName: 'Nahum', chapters: 3, testament: 'Old' },
  { id: 'hab', name: 'Habakkuk', englishName: 'Habakkuk', chapters: 3, testament: 'Old' },
  { id: 'zep', name: 'Zephania', englishName: 'Zephaniah', chapters: 3, testament: 'Old' },
  { id: 'hag', name: 'Haggai', englishName: 'Haggai', chapters: 2, testament: 'Old' },
  { id: 'zec', name: 'Zekaria', englishName: 'Zechariah', chapters: 14, testament: 'Old' },
  { id: 'mal', name: 'Malaki', englishName: 'Malachi', chapters: 4, testament: 'Old' },

  // New Testament (Sastro Gital)
  { id: 'mat', name: 'Mathi', englishName: 'Matthew', chapters: 28, testament: 'New' },
  { id: 'mrk', name: 'Markos', englishName: 'Mark', chapters: 16, testament: 'New' },
  { id: 'luk', name: 'Luka', englishName: 'Luke', chapters: 24, testament: 'New' },
  { id: 'jhn', name: 'Jhon', englishName: 'John', chapters: 21, testament: 'New' },
  { id: 'act', name: 'Apostolrangni Ka·ani', englishName: 'Acts', chapters: 28, testament: 'New' },
  { id: 'rom', name: 'Romirangna', englishName: 'Romans', chapters: 16, testament: 'New' },
  { id: '1co', name: '1 Korinthirangna', englishName: '1 Corinthians', chapters: 16, testament: 'New' },
  { id: '2co', name: '2 Korinthirangna', englishName: '2 Corinthians', chapters: 13, testament: 'New' },
  { id: 'gal', name: 'Galatiarangna', englishName: 'Galatians', chapters: 6, testament: 'New' },
  { id: 'eph', name: 'Ephesorangna', englishName: 'Ephesians', chapters: 6, testament: 'New' },
  { id: 'php', name: 'Philippirangna', englishName: 'Philippians', chapters: 4, testament: 'New' },
  { id: 'col', name: 'Kolosorangna', englishName: 'Colossians', chapters: 4, testament: 'New' },
  { id: '1th', name: '1 Thessaloniarangna', englishName: '1 Thessalonians', chapters: 5, testament: 'New' },
  { id: '2th', name: '2 Thessaloniarangna', englishName: '2 Thessalonians', chapters: 3, testament: 'New' },
  { id: '1ti', name: '1 Timothina', englishName: '1 Timothy', chapters: 6, testament: 'New' },
  { id: '2ti', name: '2 Timothina', englishName: '2 Timothy', chapters: 4, testament: 'New' },
  { id: 'tit', name: 'Titusna', englishName: 'Titus', chapters: 3, testament: 'New' },
  { id: 'phm', name: 'Philemonna', englishName: 'Philemon', chapters: 1, testament: 'New' },
  { id: 'heb', name: 'Hebru·rangna', englishName: 'Hebrews', chapters: 13, testament: 'New' },
  { id: 'jas', name: 'Jakob', englishName: 'James', chapters: 5, testament: 'New' },
  { id: '1pe', name: '1 Peter', englishName: '1 Peter', chapters: 5, testament: 'New' },
  { id: '2pe', name: '2 Peter', englishName: '2 Peter', chapters: 3, testament: 'New' },
  { id: '1jn', name: '1 Jhon', englishName: '1 John', chapters: 5, testament: 'New' },
  { id: '2jn', name: '2 Jhon', englishName: '2 John', chapters: 1, testament: 'New' },
  { id: '3jn', name: '3 Jhon', englishName: '3 John', chapters: 1, testament: 'New' },
  { id: 'jud', name: 'Juda', englishName: 'Jude', chapters: 1, testament: 'New' },
  { id: 'rev', name: 'Para·pe·ani', englishName: 'Revelation', chapters: 22, testament: 'New' },
];
